import dotenv from 'dotenv';
dotenv.config();
import express from 'express';
import cookieParser from 'cookie-parser';
import authRouter from './routes/authRoutes.js';
import productRouter from './routes/productsRoute.js';
import cartRouter from './routes/cartRoutes.js';
import orderRouter from './routes/orderRoutes.js';
import paymentRouter from './routes/paymentRoutes.js';
const port = process.env.PORT ||3000;
const app=express();
app.use(express.json());
app.use(cookieParser());
app.use('/auth',authRouter);
app.use('/products',productRouter);
app.use('/carts',cartRouter);
app.use('/orders',orderRouter);
app.use('/payments',paymentRouter);
app.listen(port,()=>console.log(`server is running on ${port}`));
